#!/usr/bin/env node
// Keeps src/version.ts in lockstep with the package.json version so spans
// always report the build that produced them. Run with --check to verify
// without writing (wired into `pnpm check` and the publish workflow).
import { readFileSync, writeFileSync } from 'node:fs';

const packageJson = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const { version } = packageJson;
if (typeof version !== 'string' || version.length === 0) {
  throw new Error('package.json "version" must be a non-empty string');
}

const target = new URL('../src/version.ts', import.meta.url);
const content = [
  '// Generated by scripts/sync-version.mjs from the package.json version; do not edit by hand.',
  '// Emitted as a span attribute so traces record which extension build produced them.',
  `export const EXTENSION_VERSION = '${version}';`,
  '',
].join('\n');

if (process.argv.includes('--check')) {
  const current = readFileSync(target, 'utf8');
  if (current !== content) {
    console.error('src/version.ts is out of sync with package.json; run `pnpm sync:version`.');
    process.exit(1);
  }
} else {
  writeFileSync(target, content);
}
