// Generated by scripts/sync-version.mjs from the package.json version; do not edit by hand.
// Emitted as a span attribute so traces record which extension build produced them.
export const EXTENSION_VERSION = '0.1.0';
